package com.algorithm;

import javax.swing.*;

/**
 * @program: com.algorithm
 * @author: mashifei
 * @create: 2019-06-02-15
 */
public class Calculator extends JFrame {

    /**
     * Creates new form Calculator
     */
    // 判断是否是运算符前后的第一个数字
    private boolean firstDigit = true;
    // 判断操作是否合法
    private boolean operateValidFlag = true;
    //运算符
    String operateCommand = "=";
    //运算符前后的运算数字
    double op1 ;
    double op2;
    //功能键组M的变量
    double memory ;



    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        resultText = new javax.swing.JTextField();
        MemoryClearButton = new javax.swing.JButton();
        MemoryRecallButton = new javax.swing.JButton();
        MemoryAddButton = new javax.swing.JButton();
        MemorySubstrctButton = new javax.swing.JButton();
        MemorySaveButton = new javax.swing.JButton();
        MemoryButton = new javax.swing.JButton();
        PlusMinusButton = new javax.swing.JButton();
        B0Button = new javax.swing.JButton();
        EqualButton = new javax.swing.JButton();
        PointButton = new javax.swing.JButton();
        PercentButton = new javax.swing.JButton();
        SqrtButton = new javax.swing.JButton();
        ReciprocalButton = new javax.swing.JButton();
        DivideButton = new javax.swing.JButton();
        B7Button = new javax.swing.JButton();
        B9Button = new javax.swing.JButton();
        B8Button = new javax.swing.JButton();
        MultiplyButton = new javax.swing.JButton();
        B4Button = new javax.swing.JButton();
        B5Button = new javax.swing.JButton();
        B6Button = new javax.swing.JButton();
        SubtractButton = new javax.swing.JButton();
        B2Button = new javax.swing.JButton();
        B1Button = new javax.swing.JButton();
        B3Button = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        ClearEnterButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        BackspaceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jToolBar1.setRollover(true);

        jLabel1.setText("查看(V)");
        jToolBar1.add(jLabel1);

        jToolBar2.setRollover(true);

        jLabel2.setText("编辑(E)");
        jToolBar2.add(jLabel2);

        jToolBar3.setRollover(true);

        jLabel3.setText("帮助(H)");
        jToolBar3.add(jLabel3);

        resultText.setEditable(false);
        resultText.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        resultText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultText.setText("0");
        resultText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTextActionPerformed(evt);
            }
        });

        MemoryClearButton.setText("MC");
        MemoryClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemoryClearButtonActionPerformed(evt);
            }
        });

        MemoryRecallButton.setText("MR");
        MemoryRecallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemoryRecallButtonActionPerformed(evt);
            }
        });

        MemoryAddButton.setText("M+");
        MemoryAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemoryAddButtonActionPerformed(evt);
            }
        });

        MemorySubstrctButton.setText("M-");
        MemorySubstrctButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemorySubstrctButtonActionPerformed(evt);
            }
        });

        MemorySaveButton.setText("MS");
        MemorySaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemorySaveButtonActionPerformed(evt);
            }
        });

        MemoryButton.setText("M");
        MemoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemoryButtonActionPerformed(evt);
            }
        });

        PlusMinusButton.setText("+/-");
        PlusMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusMinusButtonActionPerformed(evt);
            }
        });

        B0Button.setText("0");
        B0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0ButtonActionPerformed(evt);
            }
        });

        EqualButton.setText("=");
        EqualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualButtonActionPerformed(evt);
            }
        });

        PointButton.setText(".");
        PointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PointButtonActionPerformed(evt);
            }
        });

        PercentButton.setText("%");
        PercentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentButtonActionPerformed(evt);
            }
        });

        SqrtButton.setText("√");
        SqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqrtButtonActionPerformed(evt);
            }
        });

        ReciprocalButton.setText("1/x");
        ReciprocalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReciprocalButtonActionPerformed(evt);
            }
        });

        DivideButton.setText("/");
        DivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideButtonActionPerformed(evt);
            }
        });

        B7Button.setText("7");
        B7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ButtonActionPerformed(evt);
            }
        });

        B9Button.setText("9");
        B9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ButtonActionPerformed(evt);
            }
        });

        B8Button.setText("8");
        B8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ButtonActionPerformed(evt);
            }
        });

        MultiplyButton.setText("*");
        MultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyButtonActionPerformed(evt);
            }
        });

        B4Button.setText("4");
        B4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ButtonActionPerformed(evt);
            }
        });

        B5Button.setText("5");
        B5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ButtonActionPerformed(evt);
            }
        });

        B6Button.setText("6");
        B6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ButtonActionPerformed(evt);
            }
        });

        SubtractButton.setText("-");
        SubtractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractButtonActionPerformed(evt);
            }
        });

        B2Button.setText("2");
        B2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ButtonActionPerformed(evt);
            }
        });

        B1Button.setText("1");
        B1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ButtonActionPerformed(evt);
            }
        });

        B3Button.setText("3");
        B3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ButtonActionPerformed(evt);
            }
        });

        AddButton.setText("+");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        ClearEnterButton.setText("CE");
        ClearEnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearEnterButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("C");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        BackspaceButton.setText("←");
        BackspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackspaceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(PlusMinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(PointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(ClearEnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BackspaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(MemoryClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MemoryRecallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MemoryAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MemorySubstrctButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MemorySaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MemoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                                .addComponent(PercentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(SqrtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                                .addComponent(B7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(B8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                                .addComponent(B9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(MultiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                                .addComponent(ReciprocalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(DivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                                .addComponent(B1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(B2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                                .addComponent(B4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(B5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                                .addComponent(B6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(SubtractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                                .addComponent(B3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(resultText)))
        );
        jInternalFrame1Layout.setVerticalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(MemoryClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MemoryRecallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MemoryAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MemorySubstrctButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MemorySaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MemoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ClearEnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BackspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PercentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SqrtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ReciprocalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(B7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MultiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(B4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SubtractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(B2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PlusMinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>

    private void MemorySubstrctButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "M-";
        double op2 = Double.parseDouble(resultText.getText());
        resultText.setText((op2 - memory) +"");
    }



    /**
     * @author Yanboooooooo
     * 数字键0-9
     */
    private void B1ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String key = "1";
        if (firstDigit) {
            resultText.setText(key);
        } else if ((key.equals(".")) && (resultText.getText().indexOf(".") < 0)) {
            resultText.setText(resultText.getText() + ".");
        } else if (!key.equals(".")) {
            resultText.setText(resultText.getText() + key);
        }
        firstDigit = false;
    }

    private void resultTextActionPerformed(java.awt.event.ActionEvent evt) {


    }

    private void B0ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String key = "0";
        //测试  ResultText.setText("1");
        if (firstDigit) {
            // 输入的第一个数字
            resultText.setText(key);
        } else if ((key.equals(".")) && (resultText.getText().indexOf(".") < 0)) {
            // 输入的是小数点，并且之前没有小数点，则将小数点附在结果文本框的后面
            resultText.setText(resultText.getText() + ".");
        } else if (!key.equals(".")) {
            // 如果输入的不是小数点，则将数字附在结果文本框的后面
            resultText.setText(resultText.getText() + key);
        }
        // 以后输入的肯定不是第一个数字了
        firstDigit = false;
    }

    private void B2ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String key = "2";
        if (firstDigit) {
            resultText.setText(key);
        } else if ((key.equals(".")) && (resultText.getText().indexOf(".") < 0)) {
            resultText.setText(resultText.getText() + ".");
        } else if (!key.equals(".")) {
            resultText.setText(resultText.getText() + key);
        }
        firstDigit = false;
    }

    private void B3ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String key = "3";
        if (firstDigit) {
            resultText.setText(key);
        } else if ((key.equals(".")) && (resultText.getText().indexOf(".") < 0)) {
            resultText.setText(resultText.getText() + ".");
        } else if (!key.equals(".")) {
            resultText.setText(resultText.getText() + key);
        }
        firstDigit = false;
    }

    private void B4ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String key = "4";
        if (firstDigit) {
            resultText.setText(key);
        } else if ((key.equals(".")) && (resultText.getText().indexOf(".") < 0)) {
            resultText.setText(resultText.getText() + ".");
        } else if (!key.equals(".")) {
            resultText.setText(resultText.getText() + key);
        }
        firstDigit = false;
    }

    private void B5ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String key = "5";
        if (firstDigit) {
            resultText.setText(key);
        } else if ((key.equals(".")) && (resultText.getText().indexOf(".") < 0)) {
            resultText.setText(resultText.getText() + ".");
        } else if (!key.equals(".")) {
            resultText.setText(resultText.getText() + key);
        }
        firstDigit = false;
    }

    private void B6ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String key = "6";
        if (firstDigit) {
            resultText.setText(key);
        } else if ((key.equals(".")) && (resultText.getText().indexOf(".") < 0)) {
            resultText.setText(resultText.getText() + ".");
        } else if (!key.equals(".")) {
            resultText.setText(resultText.getText() + key);
        }
        firstDigit = false;
    }

    private void B7ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String key = "7";
        if (firstDigit) {
            resultText.setText(key);
        } else if ((key.equals(".")) && (resultText.getText().indexOf(".") < 0)) {
            resultText.setText(resultText.getText() + ".");
        } else if (!key.equals(".")) {
            resultText.setText(resultText.getText() + key);
        }
        firstDigit = false;
    }

    private void B8ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String key = "8";
        if (firstDigit) {
            resultText.setText(key);
        } else if ((key.equals(".")) && (resultText.getText().indexOf(".") < 0)) {
            resultText.setText(resultText.getText() + ".");
        } else if (!key.equals(".")) {
            resultText.setText(resultText.getText() + key);
        }
        firstDigit = false;
    }

    private void B9ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String key = "9";
        if (firstDigit) {
            resultText.setText((key)+"");
        } else if ((key.equals(".")) && (resultText.getText().indexOf(".") < 0)) {
            resultText.setText(resultText.getText() + ".");
        } else if (!key.equals(".")) {
            resultText.setText(resultText.getText() + key);
        }
        firstDigit = false;
    }


    /**
     * @author Yanboooooooo
     * CE、退格、C功能键
     */
    private void ClearEnterButtonActionPerformed(java.awt.event.ActionEvent evt) {
        resultText.setText("0");
    }

    private void BackspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String text = resultText.getText();
        int i = text.length();
        if (i > 0) {
            text = text.substring(0, i - 1);
            if (text.length() == 0) {
                resultText.setText("0");
                firstDigit = true;
                operateCommand = "=";
            } else {
                resultText.setText(text);
            }
        }
    }

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {
        resultText.setText("0");
        firstDigit = true;
        operateCommand = "=";
    }


    /**
     * @author Yanboooooooo
     * 加减乘除
     */
    private void DivideButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "/";
        op1 = Double.parseDouble(resultText.getText());
        //System.out.println("op1="+op1);
        firstDigit = true;
        operateValidFlag = true;
    }

    private void MultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "*";
        op1 = Double.parseDouble(resultText.getText());
        firstDigit = true;
        operateValidFlag = true;
    }

    private void SubtractButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "-";
        op1 = Double.parseDouble(resultText.getText());
        firstDigit = true;
        operateValidFlag = true;
    }

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "+";
        op1 = Double.parseDouble(resultText.getText());
        firstDigit = true;
        operateValidFlag = true;
    }



    /**
     * @author Yanboooooooo
     * 倒数、开根号、百分数、正负数、等号
     */
    private void ReciprocalButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "(1/x)";
        op1 = Double.parseDouble(resultText.getText());
        if (op1 == 0.0) {
            operateValidFlag = false;
            resultText.setText("零没有倒数");
        } else {
            resultText.setText(1 / op1+"");
        }
        firstDigit = true;
        operateValidFlag = true;
        op1= 0 ;
    }

    private void SqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "√";
        op1 = Double.parseDouble(resultText.getText());
        resultText.setText(Math.sqrt(op1)+"");
        firstDigit = true;
        operateValidFlag = true;
        op1 = 0;
    }

    private void PercentButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "%";
        op1 = Double.parseDouble(resultText.getText());
        resultText.setText(op1 / 100 +"");
        firstDigit = true;
        operateValidFlag = true;
        op1 = 0;
    }

    private void EqualButtonActionPerformed(java.awt.event.ActionEvent evt) {
        op2 = Double.parseDouble(resultText.getText());
        //System.out.println("0p2="+op2);
        switch(operateCommand){
            case "/":
            {
                if(op2 == 0){
                    resultText.setText("除数不能为零！");
                }else {
                    double x = op1;
                    double y = op2;
                    double z = x/y;
                    resultText.setText(z + "");
                    x =z;
                    firstDigit = true;
                    operateValidFlag = true;
                }
                break;
            }



            case "*":
            {
                resultText.setText(op1 * op2 + "");
                firstDigit = true;
                operateValidFlag = true;
                op1 = 0;
                break;
            }





            case"-":
            {
                resultText.setText(op1 - op2 + "");
                firstDigit = true;
                operateValidFlag = true;
                op1 = 0;
                break;
            }




            case"+":
            {
                resultText.setText(op1 + op2 + "");
                firstDigit = true;
                operateValidFlag = true;
                op1 = 0;
                break;
            }
        }
    }

    private void PlusMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "+/-";
        op1 = Double.parseDouble(resultText.getText());
        resultText.setText(op1 * (-1)+"");
        firstDigit = true;
        operateValidFlag = true;
        op1 = 0;
    }




    private void MemoryButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "M";
    }

    private void MemorySaveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "MS";
        double op2 = Double.parseDouble(resultText.getText());
        memory = op2 ;
    }

    private void MemoryAddButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "M+";
        double op2 = Double.parseDouble(resultText.getText());
        resultText.setText((op2 + memory) +"");
    }

    private void MemoryRecallButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "MR";
        resultText.setText(memory + "");
    }

    private void MemoryClearButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = "MC";
        memory = 0 ;
    }

    private void PointButtonActionPerformed(java.awt.event.ActionEvent evt) {
        operateCommand = ".";
        if ((operateCommand.equals(".")) && (resultText.getText().indexOf(".") < 0)) {
            resultText.setText(resultText.getText() + ".");
        }
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton AddButton;
    private javax.swing.JButton B0Button;
    private javax.swing.JButton B1Button;
    private javax.swing.JButton B2Button;
    private javax.swing.JButton B3Button;
    private javax.swing.JButton B4Button;
    private javax.swing.JButton B5Button;
    private javax.swing.JButton B6Button;
    private javax.swing.JButton B7Button;
    private javax.swing.JButton B8Button;
    private javax.swing.JButton B9Button;
    private javax.swing.JButton BackspaceButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ClearEnterButton;
    private javax.swing.JButton DivideButton;
    private javax.swing.JButton EqualButton;
    private javax.swing.JButton MemoryAddButton;
    private javax.swing.JButton MemoryButton;
    private javax.swing.JButton MemoryClearButton;
    private javax.swing.JButton MemoryRecallButton;
    private javax.swing.JButton MemorySaveButton;
    private javax.swing.JButton MemorySubstrctButton;
    private javax.swing.JButton MultiplyButton;
    private javax.swing.JButton PercentButton;
    private javax.swing.JButton PlusMinusButton;
    private javax.swing.JButton PointButton;
    private javax.swing.JButton ReciprocalButton;
    private javax.swing.JButton SqrtButton;
    private javax.swing.JButton SubtractButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JTextField resultText;
    // End of variables declaration
}
